//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t __Z3addii(int64_t a1, int64_t a2);
int64_t __Z9factoriali(int32_t a1);
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE13__get_pointerB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE18__get_long_pointerB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE19__get_short_pointerB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE4dataB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9__is_longB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentrycvbB8ne200100Ev(int64_t * a1);
int64_t __ZNKSt3__118_SentinelValueFillINS_11char_traitsIcEEE5__getB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__118_SentinelValueFillINS_11char_traitsIcEEE8__is_setB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEE6failedB8ne200100Ev(int64_t * a1);
int64_t __ZNKSt3__15ctypeIcE5widenB8ne200100Ec(int64_t a1, char a2, int64_t a3, int64_t a4);
int64_t __ZNKSt3__18ios_base5flagsB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__18ios_base5rdbufB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__18ios_base5widthB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE4fillB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE5rdbufB8ne200100Ev(int64_t a1);
int64_t __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE5widenB8ne200100Ec(int64_t a1, int64_t a2);
int64_t __ZNSt3__111char_traitsIcE3eofB8ne200100Ev(void);
int64_t __ZNSt3__111char_traitsIcE6lengthB8ne200100EPKc(int64_t a1);
int64_t __ZNSt3__112__to_addressB8ne200100IKcEEPT_S3_(int64_t result);
int64_t __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1B8ne200100Emc(int64_t * a1, int64_t a2, char a3);
int64_t __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2B8ne200100Emc(int64_t a1, int64_t a2, char a3);
int64_t __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsB8ne200100EPFRS3_S4_E(int64_t a1, int64_t a2);
int64_t __ZNSt3__114pointer_traitsIPKcE10pointer_toB8ne200100ERS1_(int64_t result);
int64_t __ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE5sputnB8ne200100EPKcl(int64_t result, int64_t a2, int64_t a3);
int64_t __ZNSt3__116__non_trivial_ifILb1ENS_9allocatorIcEEEC2B8ne200100Ev(int64_t a1);
int64_t __ZNSt3__116__pad_and_outputB8ne200100IcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_(int64_t result, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t __ZNSt3__118__constexpr_strlenB8ne200100IcEEmPKT_(int64_t a1);
int64_t __ZNSt3__118_SentinelValueFillINS_11char_traitsIcEEEaSB8ne200100Ei(int64_t result, int64_t a2);
int64_t __ZNSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEEC1B8ne200100ERNS_13basic_ostreamIcS2_EE(int64_t * a1, int64_t a2);
int64_t __ZNSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEEC2B8ne200100ERNS_13basic_ostreamIcS2_EE(int64_t result, int64_t a2);
int64_t __ZNSt3__124__put_character_sequenceB8ne200100IcNS_11char_traitsIcEEEERNS_13basic_ostreamIT_T0_EES7_PKS4_m(int64_t result, int64_t a2, int64_t a3);
int64_t __ZNSt3__18ios_base5widthB8ne200100El(int64_t a1, int64_t a2);
int64_t __ZNSt3__18ios_base8setstateB8ne200100Ej(int64_t a1, int32_t a2);
int64_t __ZNSt3__19allocatorIcEC1B8ne200100Ev(int64_t a1);
int64_t __ZNSt3__19allocatorIcEC2B8ne200100Ev(int64_t a1);
int64_t __ZNSt3__19basic_iosIcNS_11char_traitsIcEEE8setstateB8ne200100Ej(int64_t a1, int64_t a2);
int64_t __ZNSt3__19use_facetB8ne200100INS_5ctypeIcEEEERKT_RKNS_6localeE(int64_t a1);
int64_t __ZNSt3__1lsB8ne200100INS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc(int64_t a1, char * a2);

// --------------------- Global Variables ---------------------

int64_t g1 = -0x7feffffffffffff7; // 0x100002048
int64_t g2 = -0x7feffffffffffff6; // 0x100002050

// ------- Dynamically Linked Functions Without Header --------

int64_t __ZNKSt3__16locale9use_facetERNS0_2idE(int64_t a1, int64_t a2);
int64_t __ZNKSt3__18ios_base6getlocEv(int64_t * a1, int64_t a2);
int64_t __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEmc(int64_t a1, int64_t a2, char a3);
int64_t __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev(int64_t a1);
int64_t __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_(int64_t * a1, int64_t a2);
int64_t __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev(int64_t a1);
int64_t __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEi(int64_t a1, int64_t a2);
int64_t __ZNSt3__16localeD1Ev(int64_t * a1);
int64_t __ZNSt3__18ios_base5clearEj(int64_t a1, int32_t a2);
int32_t _strlen(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100000500 - 0x100000512
int64_t __Z3addii(int64_t a1, int64_t a2) {
    // 0x100000500
    return a2 + a1 & 0xffffffff;
}

// Address range: 0x100000520 - 0x10000055f
int64_t __Z9factoriali(int32_t a1) {
    int64_t result = 1; // 0x10000052f
    if (a1 > 1) {
        // 0x10000053a
        result = (int32_t)__Z9factoriali(a1 - 1) * a1;
    }
    // 0x100000556
    return result;
}

// Address range: 0x100000560 - 0x1000005f2
int main(int argc, char ** argv) {
    int64_t v1 = __ZNSt3__1lsB8ne200100INS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc(g1, "Sum: "); // 0x10000057d
    int64_t v2 = __Z3addii(3, 4); // 0x100000590
    __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsB8ne200100EPFRS3_S4_E(__ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEi(v1, v2 & 0xffffffff), 0x100000660);
    int64_t v3 = __ZNSt3__1lsB8ne200100INS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc(g1, "Factorial: "); // 0x1000005bd
    int64_t v4 = __Z9factoriali(5); // 0x1000005cb
    __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsB8ne200100EPFRS3_S4_E(__ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEi(v3, v4 & 0xffffffff), 0x100000660);
    return 0;
}

// Address range: 0x100000600 - 0x10000063f
int64_t __ZNSt3__1lsB8ne200100INS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc(int64_t a1, char * a2) {
    int64_t v1 = (int64_t)a2;
    return __ZNSt3__124__put_character_sequenceB8ne200100IcNS_11char_traitsIcEEEERNS_13basic_ostreamIT_T0_EES7_PKS4_m(a1, v1, __ZNSt3__111char_traitsIcE6lengthB8ne200100EPKc(v1));
}

// Address range: 0x100000640 - 0x10000065d
int64_t __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsB8ne200100EPFRS3_S4_E(int64_t a1, int64_t a2) {
    // 0x100000640
    int64_t result; // 0x100000640
    return result;
}

// Address range: 0x1000006b0 - 0x100000832
int64_t __ZNSt3__124__put_character_sequenceB8ne200100IcNS_11char_traitsIcEEEERNS_13basic_ostreamIT_T0_EES7_PKS4_m(int64_t result, int64_t a2, int64_t a3) {
    // 0x1000006b0
    int64_t v1; // bp-48, 0x1000006b0
    __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_(&v1, result);
    uint64_t v2 = __ZNKSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentrycvbB8ne200100Ev(&v1); // 0x1000006da
    if (v2 % 2 == 0) {
        // 0x100000827
        __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev((int64_t)&v1);
        return result;
    }
    // 0x1000006f0
    int64_t v3; // bp-80, 0x1000006b0
    __ZNSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEEC1B8ne200100ERNS_13basic_ostreamIcS2_EE(&v3, result);
    int64_t * v4 = (int64_t *)(result - 24); // 0x10000070c
    int64_t v5 = (__ZNKSt3__18ios_base5flagsB8ne200100Ev(*v4 + result) & 176) != 32 ? 0 : a3;
    int64_t v6 = *v4 + result; // 0x100000762
    int64_t v7 = __ZNSt3__116__pad_and_outputB8ne200100IcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_(v3, a2, v5 + a2, a3 + a2, v6, 0x100000000000000 * __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE4fillB8ne200100Ev(v6) >> 56); // bp-72, 0x1000007a3
    if (__ZNKSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEE6failedB8ne200100Ev(&v7) % 2 != 0) {
        // 0x1000007b6
        __ZNSt3__19basic_iosIcNS_11char_traitsIcEEE8setstateB8ne200100Ej(*v4 + result, 5);
    }
    // 0x100000827
    __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev((int64_t)&v1);
    return result;
}

// Address range: 0x100000860 - 0x10000087b
int64_t __ZNSt3__111char_traitsIcE6lengthB8ne200100EPKc(int64_t a1) {
    // 0x100000860
    return __ZNSt3__118__constexpr_strlenB8ne200100IcEEmPKT_(a1);
}

// Address range: 0x100000880 - 0x100000892
int64_t __ZNKSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentrycvbB8ne200100Ev(int64_t * a1) {
    // 0x100000880
    int64_t v1; // 0x100000880
    return (uint64_t)v1 % 2 | (int64_t)a1 & -256;
}

// Address range: 0x1000008a0 - 0x100000a80
int64_t __ZNSt3__116__pad_and_outputB8ne200100IcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_(int64_t result, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1000008a0
    if (result == 0) {
        // 0x100000a5f
        return result;
    }
    int64_t v1 = __ZNKSt3__18ios_base5widthB8ne200100Ev(a5); // 0x1000008ec
    uint64_t v2 = a3 - a2; // 0x100000920
    if (v2 >= 1) {
        // 0x10000092e
        if (__ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE5sputnB8ne200100EPKcl(result, a2, v2) != v2) {
            // 0x100000a5f
            return 0;
        }
    }
    int64_t v3 = a4 - a2; // 0x1000008e1
    uint64_t v4 = v1 > v3 ? v1 - v3 : 0;
    if (v4 >= 1) {
        // 0x100000967
        int64_t v5; // bp-112, 0x1000008a0
        int64_t v6 = &v5; // 0x100000973
        __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1B8ne200100Emc(&v5, v4, (char)a6);
        int64_t v7 = __ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE5sputnB8ne200100EPKcl(result, __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE4dataB8ne200100Ev(v6), v4); // 0x1000009a4
        __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev(v6);
        if (v7 != v4) {
            // 0x100000a5f
            return 0;
        }
    }
    uint64_t v8 = a4 - a3; // 0x100000a11
    if (v8 >= 1) {
        // 0x100000a1f
        if (__ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE5sputnB8ne200100EPKcl(result, a3, v8) != v8) {
            // 0x100000a5f
            return 0;
        }
    }
    // 0x100000a4a
    __ZNSt3__18ios_base5widthB8ne200100El(a5, 0);
    // 0x100000a5f
    return result;
}

// Address range: 0x100000a80 - 0x100000aa3
int64_t __ZNSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEEC1B8ne200100ERNS_13basic_ostreamIcS2_EE(int64_t * a1, int64_t a2) {
    // 0x100000a80
    return __ZNSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEEC2B8ne200100ERNS_13basic_ostreamIcS2_EE((int64_t)a1, a2);
}

// Address range: 0x100000ab0 - 0x100000ac1
int64_t __ZNKSt3__18ios_base5flagsB8ne200100Ev(int64_t a1) {
    // 0x100000ab0
    return (int64_t)*(int32_t *)(a1 + 8);
}

// Address range: 0x100000ad0 - 0x100000b2e
int64_t __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE4fillB8ne200100Ev(int64_t a1) {
    int64_t v1 = a1 + 144; // 0x100000ae4
    if (__ZNKSt3__118_SentinelValueFillINS_11char_traitsIcEEE8__is_setB8ne200100Ev(v1) % 2 == 0) {
        // 0x100000af4
        __ZNSt3__118_SentinelValueFillINS_11char_traitsIcEEEaSB8ne200100Ei(v1, 0x100000000000000 * __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE5widenB8ne200100Ec(a1, 32) >> 56);
    }
    // 0x100000b15
    return 0x100000000000000 * __ZNKSt3__118_SentinelValueFillINS_11char_traitsIcEEE5__getB8ne200100Ev(v1) >> 56;
}

// Address range: 0x100000b30 - 0x100000b47
int64_t __ZNKSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEE6failedB8ne200100Ev(int64_t * a1) {
    // 0x100000b30
    return (int64_t)a1 & -256 | (int64_t)(bool)(a1 == NULL);
}

// Address range: 0x100000b50 - 0x100000b71
int64_t __ZNSt3__19basic_iosIcNS_11char_traitsIcEEE8setstateB8ne200100Ej(int64_t a1, int64_t a2) {
    // 0x100000b50
    return __ZNSt3__18ios_base8setstateB8ne200100Ej(a1, (int32_t)a2);
}

// Address range: 0x100000b90 - 0x100000ba2
int64_t __ZNKSt3__18ios_base5widthB8ne200100Ev(int64_t a1) {
    // 0x100000b90
    return *(int64_t *)(a1 + 24);
}

// Address range: 0x100000bb0 - 0x100000bdc
int64_t __ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE5sputnB8ne200100EPKcl(int64_t result, int64_t a2, int64_t a3) {
    // 0x100000bb0
    return result;
}

// Address range: 0x100000be0 - 0x100000c0c
int64_t __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1B8ne200100Emc(int64_t * a1, int64_t a2, char a3) {
    // 0x100000be0
    return __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2B8ne200100Emc((int64_t)a1, a2, a3);
}

// Address range: 0x100000c10 - 0x100000c33
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE4dataB8ne200100Ev(int64_t a1) {
    // 0x100000c10
    return __ZNSt3__112__to_addressB8ne200100IKcEEPT_S3_(__ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE13__get_pointerB8ne200100Ev(a1));
}

// Address range: 0x100000c40 - 0x100000c66
int64_t __ZNSt3__18ios_base5widthB8ne200100El(int64_t a1, int64_t a2) {
    int64_t * v1 = (int64_t *)(a1 + 24); // 0x100000c50
    *v1 = a2;
    return *v1;
}

// Address range: 0x100000c70 - 0x100000ca9
int64_t __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2B8ne200100Emc(int64_t a1, int64_t a2, char a3) {
    // 0x100000c70
    __ZNSt3__19allocatorIcEC1B8ne200100Ev(a1);
    return __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEmc(a1, a2, a3);
}

// Address range: 0x100000cb0 - 0x100000ccb
int64_t __ZNSt3__19allocatorIcEC1B8ne200100Ev(int64_t a1) {
    // 0x100000cb0
    return __ZNSt3__19allocatorIcEC2B8ne200100Ev(a1);
}

// Address range: 0x100000cd0 - 0x100000ceb
int64_t __ZNSt3__19allocatorIcEC2B8ne200100Ev(int64_t a1) {
    // 0x100000cd0
    return __ZNSt3__116__non_trivial_ifILb1ENS_9allocatorIcEEEC2B8ne200100Ev(a1);
}

// Address range: 0x100000cf0 - 0x100000cfa
int64_t __ZNSt3__116__non_trivial_ifILb1ENS_9allocatorIcEEEC2B8ne200100Ev(int64_t a1) {
    // 0x100000cf0
    int64_t result; // 0x100000cf0
    return result;
}

// Address range: 0x100000d00 - 0x100000d0e
int64_t __ZNSt3__112__to_addressB8ne200100IKcEEPT_S3_(int64_t result) {
    // 0x100000d00
    return result;
}

// Address range: 0x100000d10 - 0x100000d55
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE13__get_pointerB8ne200100Ev(int64_t a1) {
    uint64_t v1 = __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9__is_longB8ne200100Ev(a1); // 0x100000d24
    int64_t result; // 0x100000d10
    if (v1 % 2 != 0) {
        // 0x100000d2f
        result = __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE18__get_long_pointerB8ne200100Ev(a1);
    } else {
        // 0x100000d3e
        result = __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE19__get_short_pointerB8ne200100Ev(a1);
    }
    // 0x100000d4b
    return result;
}

// Address range: 0x100000d60 - 0x100000d79
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9__is_longB8ne200100Ev(int64_t a1) {
    // 0x100000d60
    int64_t v1; // 0x100000d60
    return a1 & -256 | (int64_t)((uint64_t)v1 % 2 != 0);
}

// Address range: 0x100000d80 - 0x100000d92
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE18__get_long_pointerB8ne200100Ev(int64_t a1) {
    // 0x100000d80
    return *(int64_t *)(a1 + 16);
}

// Address range: 0x100000da0 - 0x100000dbf
int64_t __ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE19__get_short_pointerB8ne200100Ev(int64_t a1) {
    // 0x100000da0
    return __ZNSt3__114pointer_traitsIPKcE10pointer_toB8ne200100ERS1_(a1 + 1);
}

// Address range: 0x100000dc0 - 0x100000dce
int64_t __ZNSt3__114pointer_traitsIPKcE10pointer_toB8ne200100ERS1_(int64_t result) {
    // 0x100000dc0
    return result;
}

// Address range: 0x100000dd0 - 0x100000e12
int64_t __ZNSt3__119ostreambuf_iteratorIcNS_11char_traitsIcEEEC2B8ne200100ERNS_13basic_ostreamIcS2_EE(int64_t result, int64_t a2) {
    int64_t v1 = __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE5rdbufB8ne200100Ev(*(int64_t *)(a2 - 24) + a2); // 0x100000df6
    *(int64_t *)result = v1;
    return result;
}

// Address range: 0x100000e20 - 0x100000e3b
int64_t __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE5rdbufB8ne200100Ev(int64_t a1) {
    // 0x100000e20
    return __ZNKSt3__18ios_base5rdbufB8ne200100Ev(a1);
}

// Address range: 0x100000e40 - 0x100000e52
int64_t __ZNKSt3__18ios_base5rdbufB8ne200100Ev(int64_t a1) {
    // 0x100000e40
    return *(int64_t *)(a1 + 40);
}

// Address range: 0x100000e60 - 0x100000e8c
int64_t __ZNKSt3__118_SentinelValueFillINS_11char_traitsIcEEE8__is_setB8ne200100Ev(int64_t a1) {
    // 0x100000e60
    int64_t v1; // 0x100000e60
    int64_t v2 = v1;
    return v2 & 0xffffff00 | (int64_t)((int32_t)v2 != (int32_t)__ZNSt3__111char_traitsIcE3eofB8ne200100Ev());
}

// Address range: 0x100000e90 - 0x100000ee9
int64_t __ZNKSt3__19basic_iosIcNS_11char_traitsIcEEE5widenB8ne200100Ec(int64_t a1, int64_t a2) {
    // 0x100000e90
    int64_t v1; // bp-32, 0x100000e90
    __ZNKSt3__18ios_base6getlocEv(&v1, a1);
    int64_t v2 = __ZNSt3__19use_facetB8ne200100INS_5ctypeIcEEEERKT_RKNS_6localeE((int64_t)&v1); // 0x100000eb7
    int64_t v3; // 0x100000e90
    int64_t v4 = __ZNKSt3__15ctypeIcE5widenB8ne200100Ec(v2, (char)a2, v3, v3); // 0x100000eca
    __ZNSt3__16localeD1Ev(&v1);
    return 0x100000000000000 * v4 >> 56;
}

// Address range: 0x100000f10 - 0x100000f26
int64_t __ZNSt3__118_SentinelValueFillINS_11char_traitsIcEEEaSB8ne200100Ei(int64_t result, int64_t a2) {
    // 0x100000f10
    *(int32_t *)result = (int32_t)a2;
    return result;
}

// Address range: 0x100000f30 - 0x100000f40
int64_t __ZNKSt3__118_SentinelValueFillINS_11char_traitsIcEEE5__getB8ne200100Ev(int64_t a1) {
    // 0x100000f30
    int64_t v1; // 0x100000f30
    return v1 & 0xffffffff;
}

// Address range: 0x100000f40 - 0x100000f4b
int64_t __ZNSt3__111char_traitsIcE3eofB8ne200100Ev(void) {
    // 0x100000f40
    return 0xffffffff;
}

// Address range: 0x100000f50 - 0x100000f72
int64_t __ZNSt3__19use_facetB8ne200100INS_5ctypeIcEEEERKT_RKNS_6localeE(int64_t a1) {
    // 0x100000f50
    return __ZNKSt3__16locale9use_facetERNS0_2idE(a1, g2);
}

// Address range: 0x100000f80 - 0x100000fab
int64_t __ZNKSt3__15ctypeIcE5widenB8ne200100Ec(int64_t a1, char a2, int64_t a3, int64_t a4) {
    // 0x100000f80
    return 0x100000000000000 * a1 >> 56;
}

// Address range: 0x100000fb0 - 0x100000fd4
int64_t __ZNSt3__18ios_base8setstateB8ne200100Ej(int64_t a1, int32_t a2) {
    // 0x100000fb0
    return __ZNSt3__18ios_base5clearEj(a1, *(int32_t *)(a1 + 32) | a2);
}

// Address range: 0x100000fe0 - 0x100000ffb
int64_t __ZNSt3__118__constexpr_strlenB8ne200100IcEEmPKT_(int64_t a1) {
    // 0x100000fe0
    return _strlen((char *)a1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: embarcadero delphi
// Detected functions: 41

